USE [AP_INVENTORY]
GO

/***********************/
/* LOAD CALENDAR TABLE */
/***********************/

TRUNCATE TABLE [MASTER_DATA].[CALENDAR]
GO

DECLARE @StartDate DATE;
DECLARE @StopDate DATE;
DECLARE @CurrentDate DATE;

SET @StartDate = '01/01/2002'
SET @StopDate = '12/31/2022'

SET @CurrentDate = @StartDate

WHILE (@CurrentDate <= @StopDate)
BEGIN

INSERT INTO [MASTER_DATA].[CALENDAR]
VALUES (
CONVERT(INT,
(
CONVERT(VARCHAR,YEAR(@CurrentDate)) +
CONVERT(VARCHAR,DATEPART(qq,@CurrentDate)) +
CONVERT(VARCHAR,MONTH(@CurrentDate)) +
CONVERT(VARCHAR,DAY(@CurrentDate))
)
),
YEAR(@CurrentDate),
DATEPART(qq,@CurrentDate),
MONTH(@CurrentDate),
@CurrentDate
);

SET @CurrentDate = DATEADD(dd,1,@CurrentDate);
END
GO

/********************/
/* LOAD DIM.COUNTRY */
/********************/

TRUNCATE TABLE [MASTER_DATA].[COUNTRY]
GO

INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Afghanistan','AF','AFG')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Aland Islands','AX','ALA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Albania','AL','ALB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Algeria','DZ','DZA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('American Samoa','AS','ASM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Andorra','AD','AND')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Angola','AO','AGO')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Anguilla','AI','AIA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Antarctica','AQ','ATA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Antigua and Barbuda','AG','ATG')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Argentina','AR','ARG')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Armenia','AM','ARM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Aruba','AW','ABW')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Australia','AU','AUS')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Austria','AT','AUT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Azerbaijan','AZ','AZE')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Bahamas','BS','BHS')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Bahrain','BH','BHR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Bangladesh','BD','BGD')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Barbados','BB','BRB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Belarus','BY','BLR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Belgium','BE','BEL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Belize','BZ','BLZ')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Benin','BJ','BEN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Bermuda','BM','BMU')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Bhutan','BT','BTN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Bolivia','BO','BOL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Bosnia and Herzegovina','BA','BIH')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Botswana','BW','BWA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Bouvet Island','BV','BVT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Brazil','BR','BRA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('British Indian Ocean Territory','IO','IOT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('British Virgin Islands','VG','VGB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Brunei Darussalam','BN','BRN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Bulgaria','BG','BGR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Burkina Faso','BF','BFA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Burundi','BI','BDI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Cambodia','KH','KHM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Cameroon','CM','CMR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Canada','CA','CAN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Cape Verde','CV','CPV')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Cayman Islands','KY','CYM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Central African Republic','CF','CAF')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Chad','TD','TCD')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Chile','CL','CHL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('China','CN','CHN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Christmas Island','CX','CXR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Cocos (Keeling) Islands','CC','CCK')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Colombia','CO','COL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Comoros','KM','COM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Congo (Brazzaville)','CG','COG')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Congo, (Kinshasa)','CD','COD')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Cook Islands','CK','COK')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Costa Rica','CR','CRI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Côte d''Ivoire','CI','CIV')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Croatia','HR','HRV')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Cuba','CU','CUB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Cyprus','CY','CYP')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Czech Republic','CZ','CZE')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Denmark','DK','DNK')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Djibouti','DJ','DJI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Dominica','DM','DMA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Dominican Republic','DO','DOM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Ecuador','EC','ECU')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Egypt','EG','EGY')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('El Salvador','SV','SLV')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Equatorial Guinea','GQ','GNQ')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Eritrea','ER','ERI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Estonia','EE','EST')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Ethiopia','ET','ETH')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Falkland Islands (Malvinas)','FK','FLK')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Faroe Islands','FO','FRO')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Fiji','FJ','FJI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Finland','FI','FIN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('France','FR','FRA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('French Guiana','GF','GUF')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('French Polynesia','PF','PYF')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('French Southern Territories','TF','ATF')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Gabon','GA','GAB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Gambia','GM','GMB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Georgia','GE','GEO')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Germany','DE','DEU')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Ghana','GH','GHA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Gibraltar','GI','GIB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Greece','GR','GRC')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Greenland','GL','GRL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Grenada','GD','GRD')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Guadeloupe','GP','GLP')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Guam','GU','GUM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Guatemala','GT','GTM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Guernsey','GG','GGY')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Guinea','GN','GIN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Guinea-Bissau','GW','GNB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Guyana','GY','GUY')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Haiti','HT','HTI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Heard and Mcdonald Islands','HM','HMD')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Holy See (Vatican City State)','VA','VAT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Honduras','HN','HND')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Hong Kong, SAR China','HK','HKG')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Hungary','HU','HUN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Iceland','IS','ISL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('India','IN','IND')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Indonesia','ID','IDN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Iran, Islamic Republic of','IR','IRN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Iraq','IQ','IRQ')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Ireland','IE','IRL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Isle of Man','IM','IMN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Israel','IL','ISR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Italy','IT','ITA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Jamaica','JM','JAM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Japan','JP','JPN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Jersey','JE','JEY')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Jordan','JO','JOR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Kazakhstan','KZ','KAZ')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Kenya','KE','KEN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Kiribati','KI','KIR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Korea (North)','KP','PRK')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Korea (South)','KR','KOR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Kuwait','KW','KWT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Kyrgyzstan','KG','KGZ')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Lao PDR','LA','LAO')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Latvia','LV','LVA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Lebanon','LB','LBN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Lesotho','LS','LSO')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Liberia','LR','LBR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Libya','LY','LBY')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Liechtenstein','LI','LIE')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Lithuania','LT','LTU')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Luxembourg','LU','LUX')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Macao, SAR China','MO','MAC')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Macedonia, Republic of','MK','MKD')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Madagascar','MG','MDG')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Malawi','MW','MWI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Malaysia','MY','MYS')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Maldives','MV','MDV')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Mali','ML','MLI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Malta','MT','MLT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Marshall Islands','MH','MHL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Martinique','MQ','MTQ')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Mauritania','MR','MRT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Mauritius','MU','MUS')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Mayotte','YT','MYT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Mexico','MX','MEX')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Micronesia, Federated States of','FM','FSM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Moldova','MD','MDA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Monaco','MC','MCO')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Mongolia','MN','MNG')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Montenegro','ME','MNE')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Montserrat','MS','MSR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Morocco','MA','MAR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Mozambique','MZ','MOZ')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Myanmar','MM','MMR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Namibia','NA','NAM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Nauru','NR','NRU')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Nepal','NP','NPL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Netherlands','NL','NLD')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Netherlands Antilles','AN','ANT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('New Caledonia','NC','NCL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('New Zealand','NZ','NZL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Nicaragua','NI','NIC')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Niger','NE','NER')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Nigeria','NG','NGA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Niue','NU','NIU')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Norfolk Island','NF','NFK')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Northern Mariana Islands','MP','MNP')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Norway','NO','NOR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Oman','OM','OMN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Pakistan','PK','PAK')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Palau','PW','PLW')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Palestinian Territory','PS','PSE')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Panama','PA','PAN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Papua New Guinea','PG','PNG')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Paraguay','PY','PRY')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Peru','PE','PER')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Philippines','PH','PHL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Pitcairn','PN','PCN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Poland','PL','POL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Portugal','PT','PRT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Puerto Rico','PR','PRI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Qatar','QA','QAT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Réunion','RE','REU')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Romania','RO','ROU')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Russian Federation','RU','RUS')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Rwanda','RW','RWA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Saint Helena','SH','SHN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Saint Kitts and Nevis','KN','KNA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Saint Lucia','LC','LCA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Saint Pierre and Miquelon','PM','SPM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Saint Vincent and Grenadines','VC','VCT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Saint-Barthélemy','BL','BLM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Saint-Martin (French part)','MF','MAF')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Samoa','WS','WSM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('San Marino','SM','SMR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Sao Tome and Principe','ST','STP')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Saudi Arabia','SA','SAU')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Senegal','SN','SEN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Serbia','RS','SRB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Seychelles','SC','SYC')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Sierra Leone','SL','SLE')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Singapore','SG','SGP')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Slovakia','SK','SVK')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Slovenia','SI','SVN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Solomon Islands','SB','SLB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Somalia','SO','SOM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('South Africa','ZA','ZAF')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('South Georgia and the South Sandwich Islands','GS','SGS')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('South Sudan','SS','SSD')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Spain','ES','ESP')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Sri Lanka','LK','LKA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Sudan','SD','SDN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Suriname','SR','SUR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Svalbard and Jan Mayen Islands','SJ','SJM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Swaziland','SZ','SWZ')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Sweden','SE','SWE')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Switzerland','CH','CHE')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Syrian Arab Republic (Syria)','SY','SYR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Taiwan, Republic of China','TW','TWN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Tajikistan','TJ','TJK')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Tanzania, United Republic of','TZ','TZA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Thailand','TH','THA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Timor-Leste','TL','TLS')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Togo','TG','TGO')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Tokelau','TK','TKL')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Tonga','TO','TON')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Trinidad and Tobago','TT','TTO')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Tunisia','TN','TUN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Turkey','TR','TUR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Turkmenistan','TM','TKM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Turks and Caicos Islands','TC','TCA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Tuvalu','TV','TUV')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Uganda','UG','UGA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Ukraine','UA','UKR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('United Arab Emirates','AE','ARE')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('United Kingdom','GB','GBR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('United States','US','USA')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Uruguay','UY','URY')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('US Minor Outlying Islands','UM','UMI')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Uzbekistan','UZ','UZB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Vanuatu','VU','VUT')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Venezuela (Bolivarian Republic)','VE','VEN')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Viet Nam','VN','VNM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Virgin Islands, US','VI','VIR')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Wallis and Futuna Islands','WF','WLF')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Western Sahara','EH','ESH')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Yemen','YE','YEM')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Zambia','ZM','ZMB')
INSERT INTO [MASTER_DATA].[COUNTRY] VALUES('Zimbabwe','ZW','ZWE')
GO

/**********************/ 
/* PRODUCT_TYPE TABLE */
/**********************/
 
TRUNCATE TABLE [MASTER_DATA].[PRODUCT_TYPE]
GO

INSERT INTO [MASTER_DATA].[PRODUCT_TYPE]
VALUES
('PT01','HO Electric Locomotive'),
('PT02','HO Steam Locomotive'),
('PT03','HO Diesel Locomotive'),
('PT04','HO Passenger Car'),
('PT05','HO Freight Car'),
('PT06','N Electric Locomotive'),
('PT07','N Steam Locomotive'),
('PT08','N Diesel Locomotive'),
('PT09','N Passenger Car'),
('PT10','N Freight Car');

SELECT *
FROM [MASTER_DATA].[PRODUCT_TYPE]
GO

TRUNCATE TABLE [MASTER_DATA].[PRODUCT]
GO

/***********************/
/* LOAD HO LOCOMOTIVES */
/***********************/

DECLARE @PRODUCT TABLE (
	[PROD_ID] VARCHAR(4),
	[PROD_NAME] VARCHAR(64)
	);

INSERT INTO @PRODUCT
VALUES
('P001','French Type 1 Locomotive'),
('P005','Italian Type 1 Locomotive'),
('P009','German Type 1 Locomotive'),
('P013','Swiss Type 1 Locomotive');

--INSERT INTO [MASTER_DATA].[PRODUCT]
SELECT P.PROD_ID,P.PROD_NAME,0.0,0.0,PT.PROD_TYPE
FROM MASTER_DATA.PRODUCT_TYPE PT
CROSS JOIN @PRODUCT P
WHERE PT.PROD_TYPE_NAME LIKE '%HO Electric Locomotive'
GO

DECLARE @PRODUCT TABLE (
	[PROD_ID] VARCHAR(4),
	[PROD_NAME] VARCHAR(64)
	);

INSERT INTO @PRODUCT
VALUES
('P033','French Type 1 Locomotive'),
('P037','Italian Type 1 Locomotive'),
('P041','German Type 1 Locomotive'),
('P045','Swiss Type 1 Locomotive');

INSERT INTO [MASTER_DATA].[PRODUCT]
SELECT P.PROD_ID,P.PROD_NAME,0.0,0.0,PT.PROD_TYPE
FROM MASTER_DATA.PRODUCT_TYPE PT
CROSS JOIN @PRODUCT P
WHERE PT.PROD_TYPE_NAME LIKE '%HO Steam Locomotive'
GO

/**********************/
/* LOAD N LOCOMOTIVES */
/**********************/

DECLARE @PRODUCT TABLE (
	[PROD_ID] VARCHAR(4),
	[PROD_NAME] VARCHAR(64)
	);

INSERT INTO @PRODUCT
VALUES
('P101','French Type 1 Locomotive'),
('P105','Italian Type 1 Locomotive'),
('P109','German Type 1 Locomotive'),
('P113','Swiss Type 1 Locomotive');

INSERT INTO [MASTER_DATA].[PRODUCT]
SELECT P.PROD_ID,P.PROD_NAME,0.0,0.0,PT.PROD_TYPE
FROM MASTER_DATA.PRODUCT_TYPE PT
CROSS JOIN @PRODUCT P
WHERE PT.PROD_TYPE_NAME LIKE '%N Electric Locomotive'
GO

/**************************/
/* LOAD HO PASSENGER CARS */
/**************************/

DECLARE @PRODUCT TABLE (
	[PROD_ID] VARCHAR(4),
	[PROD_NAME] VARCHAR(64)
	);

INSERT INTO @PRODUCT
VALUES
('P201','French Type 1 Passenger Car'),
('P205','Italian Type 1 Passenger Car'),
('P209','German Type 1 Passenger Car'),
('P213','Swiss Type 1 Passenger Car');

INSERT INTO [MASTER_DATA].[PRODUCT]
SELECT P.PROD_ID,P.PROD_NAME,0.0,0.0,PT.PROD_TYPE
FROM MASTER_DATA.PRODUCT_TYPE PT
CROSS JOIN @PRODUCT P
WHERE PT.PROD_TYPE_NAME LIKE '%HO Passenger Car'
GO

/*******************/
/* HO FREIGHT CARS */
/*******************/
/*
DECLARE @PRODUCT TABLE (
	[PROD_ID] VARCHAR(4),
	[PROD_NAME] VARCHAR(64)
	);

INSERT INTO @PRODUCT
VALUES
('P317','French Type 1 Freight Car'),
('P318','French Type 2 Freight Car'),
('P319','French Type 3 Freight Car'),
('P320','French Type 4 Freight Car'),
('P321','Italian Type 1 Freight Car'),
('P322','Italian Type 2 Freight Car'),
('P323','Italian Type 3 Freight Car'),
('P324','Italian Type 4 Freight Car'),
('P325','German Type 1 Freight Car'),
('P326','German Type 2 Freight Car'),
('P327','German Type 3 Freight Car'),
('P328','German Type 4 Freight Car'),
('P329','Swiss Type 1 Freight Car'),
('P330','Swiss Type 2 Freight Car'),
('P331','Swiss Type 3 Freight Car'),
('P332','Swiss Type 4 Freight Car');

INSERT INTO [MASTER_DATA].[PRODUCT]
SELECT P.PROD_ID,P.PROD_NAME,0.0,0.0,PT.PROD_TYPE
FROM MASTER_DATA.PRODUCT_TYPE PT
CROSS JOIN @PRODUCT P
WHERE PT.PROD_TYPE_NAME LIKE '%HO Freight Car'
GO
*/
/******************************/
/* Load N Gauge Passenger Car */
/******************************/
/*
DECLARE @PRODUCT TABLE (
	[PROD_ID] VARCHAR(4),
	[PROD_NAME] VARCHAR(64)
	);

INSERT INTO @PRODUCT
VALUES
('P301','French Type 1 Passenger Car'),
('P302','French Type 2 Passenger Car'),
('P303','French Type 3 Passenger Car'),
('P304','French Type 4 Passenger Car'),
('P305','Italian Type 1 Passenger Car'),
('P306','Italian Type 2 Passenger Car'),
('P307','Italian Type 3 Passenger Car'),
('P308','Italian Type 4 Passenger Car'),
('P309','German Type 1 Passenger Car'),
('P310','German Type 2 Passenger Car'),
('P311','German Type 3 Passenger Car'),
('P312','German Type 4 Passenger Car'),
('P313','Swiss Type 1 Passenger Car'),
('P314','Swiss Type 2 Passenger Car'),
('P315','Swiss Type 3 Passenger Car'),
('P316','Swiss Type 4 Passenger Car');

INSERT INTO [MASTER_DATA].[PRODUCT]
SELECT P.PROD_ID,P.PROD_NAME,0.0,0.0,PT.PROD_TYPE
FROM MASTER_DATA.PRODUCT_TYPE PT
CROSS JOIN @PRODUCT P
WHERE PT.PROD_TYPE_NAME LIKE '%N Passenger Car'
GO
*/
/*****************************/
/* Load N Gauge Freight Cars */
/*****************************/
/*
DECLARE @PRODUCT TABLE (
	[PROD_ID] VARCHAR(4),
	[PROD_NAME] VARCHAR(64)
	);

INSERT INTO @PRODUCT
VALUES
('P417','French Type 1 Freight Car'),
('P418','French Type 2 Freight Car'),
('P419','French Type 3 Freight Car'),
('P420','French Type 4 Freight Car'),
('P421','Italian Type 1 Freight Car'),
('P422','Italian Type 2 Freight Car'),
('P423','Italian Type 3 Freight Car'),
('P424','Italian Type 4 Freight Car'),
('P425','German Type 1 Freight Car'),
('P426','German Type 2 Freight Car'),
('P427','German Type 3 Freight Car'),
('P428','German Type 4 Freight Car'),
('P429','Swiss Type 1 Freight Car'),
('P430','Swiss Type 2 Freight Car'),
('P431','Swiss Type 3 Freight Car'),
('P432','Swiss Type 4 Freight Car');

INSERT INTO [MASTER_DATA].[PRODUCT]
SELECT P.PROD_ID,P.PROD_NAME,0.0,0.0,PT.PROD_TYPE
FROM MASTER_DATA.PRODUCT_TYPE PT
CROSS JOIN @PRODUCT P
WHERE PT.PROD_TYPE_NAME LIKE '%N Freight Car'
GO
*/
/*****************/
/* UPDATE PRICES */
/*****************/

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 175.00,
	[WHOLESALE_PRICE] = 175.00 * .75
WHERE [PROD_NAME] LIKE 'French%Locomotive%'
GO

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 170.00,
	[WHOLESALE_PRICE] = 170.00 * .75
WHERE [PROD_NAME] LIKE 'Italian%Locomotive%'
GO

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 180.00,
	[WHOLESALE_PRICE] = 180.00 * .75
WHERE [PROD_NAME] LIKE 'German%Locomotive%'
GO

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 190.00,
	[WHOLESALE_PRICE] = 190.00 * .75
WHERE [PROD_NAME] LIKE 'Swiss%Locomotive%'
GO

/***********************************/
/* UPDATE PRICES ON PASSENGER CARS */
/***********************************/

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 175.00,
	[WHOLESALE_PRICE] = 175.00 * .75
WHERE [PROD_NAME] LIKE 'French%Passenger%'
GO

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 170.00,
	[WHOLESALE_PRICE] = 170.00 * .75
WHERE [PROD_NAME] LIKE 'Italian%Passenger%'
GO

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 180.00,
	[WHOLESALE_PRICE] = 180.00 * .75
WHERE [PROD_NAME] LIKE 'German%Passenger%'
GO

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 190.00,
	[WHOLESALE_PRICE] = 190.00 * .75
WHERE [PROD_NAME] LIKE 'Swiss%Passenger%'
GO

/*********************************/
/* UPDATE PRICES ON FREIGHT CARS */
/*********************************/

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 175.00,
	[WHOLESALE_PRICE] = 175.00 * .75
WHERE [PROD_NAME] LIKE 'French%Freight%'
GO

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 170.00,
	[WHOLESALE_PRICE] = 170.00 * .75
WHERE [PROD_NAME] LIKE 'Italian%Freight%'
GO

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 180.00,
	[WHOLESALE_PRICE] = 180.00 * .75
WHERE [PROD_NAME] LIKE 'German%Freight%'
GO

UPDATE [MASTER_DATA].[PRODUCT]
SET 
	[RETAIL_PRICE] = 190.00,
	[WHOLESALE_PRICE] = 190.00 * .75
WHERE [PROD_NAME] LIKE 'Swiss%Freight%'
GO

/************/
/* LOCATION */
/************/

USE [AP_INVENTORY]
GO

TRUNCATE TABLE [MASTER_DATA].[LOCATION]
GO

INSERT INTO [MASTER_DATA].[LOCATION]
VALUES
('LOC1','Eastern Inventory','United States','New York','Queens','123 New York Avenue','01234'),
('LOC2','Northern Inventory','United States','Maine','Bangor','456 Main Street','01235');

SELECT * 
FROM [MASTER_DATA].[LOCATION]
GO

/*************/
/* WAREHOUSE */
/*************/

/*************************************************/
/* USE THIS SCRIPT TO INITIALIZE WAREHOUSE TABLE */
/* FOR THE FIRST TIME.                           */
/*************************************************/

DECLARE @INVENTORY TABLE (	
	[LOC_ID] [varchar](4) NOT NULL,
	[INV_ID] [varchar](4) NOT NULL
	);

INSERT INTO @INVENTORY
VALUES
('LOC1','INV1'),
('LOC1','INV2'),
('LOC2','INV1'),
('LOC2','INV2');

/*
LOC_ID	INV_ID	WH_ID
LOC1	INV1	WH111
LOC1	INV1	WH112
LOC1	INV2	WH121
LOC1	INV2	WH122
LOC2	INV1	WH221
LOC2	INV1	WH222
LOC2	INV2	WH221
LOC2	INV2	WH222
*/

DECLARE @WAREHOUSE TABLE (	
	[LOC_ID] VARCHAR(4) NOT NULL,
	[WH_ID] [varchar](5) NOT NULL,
	[WH_NAME] [varchar](64) NOT NULL
	);

INSERT INTO @WAREHOUSE
VALUES
('LOC1','WH111','Euro Model Trains: Location 01 - Inventory 01 - Warehouse 01'),
('LOC1','WH112','Euro Model Trains: Location 01 - Inventory 01 - Warehouse 02'),
('LOC1','WH121','Euro Model Trains: Location 01 - Inventory 02 - Warehouse 01'),
('LOC1','WH122','Euro Model Trains: Location 01 - Inventory 02 - Warehouse 02'),
('LOC2','WH211','Euro Model Trains: Location 02 - Inventory 01 - Warehouse 01'),
('LOC2','WH212','Euro Model Trains: Location 02 - Inventory 01 - Warehouse 02'),
('LOC2','WH221','Euro Model Trains: Location 02 - Inventory 02 - Warehouse 01'),
('LOC2','WH222','Euro Model Trains: Location 02 - Inventory 02 - Warehouse 02');

TRUNCATE TABLE [TRANSACTION].[WAREHOUSE]

DELETE FROM [TRANSACTION].[WAREHOUSE]
WHERE [AS_OF_YEAR] <> '2001'

INSERT INTO [TRANSACTION].[WAREHOUSE]
SELECT DISTINCT L.[LOC_ID],
    I.[INV_ID],
	W.[WH_ID],
	W.[WH_NAME]
	,P.[PROD_ID]
	,0				AS [INV_OUT]
	,50				AS [INV_IN]
	,50				AS [QTY_ON_HAND]
	,100 			AS [REORDER_LEVEL]
	,2018			AS [AS_OF_YEAR]
	,12			    AS [AS_OF_MONTH]
	,'12-31-2001'	AS [AS_OF_DATE]
FROM [MASTER_DATA].[LOCATION] L
CROSS JOIN @WAREHOUSE W
CROSS JOIN @INVENTORY I
CROSS JOIN [MASTER_DATA].[PRODUCT] P
ORDER BY 1,2,3,4,5
GO

/*************************************************************************/
/* RUN THIS ONCE WAREHOUSE TABLE HAS BEEN INITIALIZED FOR THE FIRST TIME */
/* THIS WILL BE USED AS THE DRIVING TABLE FOR THE CUROSR LOGIC ONCE WE   */
/* LOAD THE INVENTORY_TRANSACTION TABLE.                                */
/*************************************************************************/

/*************************/
/* INVENTORY TRANSACTION */
/*************************/

-- 2,945,280 rows loaded in 1 minute 1 sec

-- EACH LOCATION HAS TWO WAREHOUSES

TRUNCATE TABLE [TRANSACTION].[INVENTORY_TRANSACTION]
GO

INSERT INTO [TRANSACTION].[INVENTORY_TRANSACTION]
SELECT 
      CONVERT(INT,UPPER (
		CONVERT(INT,CRYPT_GEN_RANDOM(1)
			) /	50)) AS [INCREMENT]
	 ,CONVERT(INT,UPPER (
		CONVERT(INT,CRYPT_GEN_RANDOM(1)
			) /	50)) AS [DECREMENT]
      ,CAL.CALENDAR_DATE AS [MOVEMENT_DATE]
	  ,WH.[INV_ID]
      ,WH.[LOC_ID]
      ,WH.[WH_ID]
      ,WH.[PROD_ID]
  FROM [AP_INVENTORY].[TRANSACTION].[WAREHOUSE] WH
  CROSS JOIN [MASTER_DATA].[CALENDAR] CAL
  GO

/*************/
/* WAREHOUSE */
/*************/

/**************************************/
/* EACH LOCATION HAS TWO INVENTORIES */
/**************************************/

/**************************************/
/* EACH INVENTORY HAS TWO WAREHOUSES */
/**************************************/

/*
LOC_ID	INV_ID	WH_ID
LOC1	INV1	WH111
LOC1	INV1	WH112
LOC1	INV2	WH121
LOC1	INV2	WH122
LOC2	INV1	WH221
LOC2	INV1	WH222
LOC2	INV2	WH221
LOC2	INV2	WH222
*/

/**********************************************/
/* DO NOT TRUNCATE TABLE IF YOU WANT TO KEEP  */
/* INITIALIZATION DATA AND MULTI-YEAR HISTORY */
/**********************************************/

/****************************************************/
/* USE TABLE VARIABLE TO DEFINE WAREHOUSE ID & NAME */
/****************************************************/

/****************************************************************/
/* INSERT THE TRANSACTIONS FROM THE INVENTORY TRANSACTION TABLE */
/****************************************************************/

/*
DELETE FROM [TRANSACTION].[WAREHOUSE]
WHERE [AS_OF_YEAR] <> 2001
GO
*/

INSERT INTO [TRANSACTION].[WAREHOUSE]
SELECT DISTINCT I.[LOC_ID],	
	I.[INV_ID],
	I.[WH_ID],
	WH.WH_NAME,
	I.PROD_ID,
	SUM(I.DECREMENT) AS MONTHLY_DECR,
	SUM(I.[INCREMENT]) AS MONTHLY_INCR,
	WH.[QTY_ON_HAND] + (SUM(I.[INCREMENT]) - SUM(I.[DECREMENT])) AS QTY_ON_HAND,
	100	AS [REORDER_LEVEL],
    YEAR(I.[MOVEMENT_DATE]),
	MONTH(I.[MOVEMENT_DATE]),
	EOMONTH(CONVERT(VARCHAR,YEAR(I.[MOVEMENT_DATE])),(MONTH(I.[MOVEMENT_DATE]) - 1))
FROM [TRANSACTION].[INVENTORY_TRANSACTION] I
JOIN (
SELECT DISTINCT [LOC_ID]
      ,[INV_ID]
      ,[WH_ID]
      ,[WH_NAME]
	  ,[QTY_ON_HAND]
  FROM [AP_INVENTORY].[TRANSACTION].[WAREHOUSE]
) WH
ON I.WH_ID = WH.WH_ID
GROUP BY	
	I.[INV_ID],
	I.[LOC_ID],
	I.[WH_ID],
	WH.[WH_ID],
	I.PROD_ID,
	WH.WH_NAME,
	WH.[QTY_ON_HAND],
	YEAR(I.[MOVEMENT_DATE]),
	MONTH(I.[MOVEMENT_DATE])
ORDER BY	
	I.[INV_ID],
	I.[LOC_ID],
	I.[WH_ID],
	I.PROD_ID,
	YEAR(I.[MOVEMENT_DATE]),
	MONTH(I.[MOVEMENT_DATE]);
GO

/****************/
/* CHECK IT OUT */
/****************/

DROP INDEX IF EXISTS [TRANSACTION].[IE_WAREHOUSE]
GO

CREATE CLUSTERED INDEX IE_WAREHOUSE ON [TRANSACTION].[WAREHOUSE](
	[INV_ID],[LOC_ID],[WH_ID] ,[PROD_ID]
	);
GO

SELECT [INV_ID]
      ,[LOC_ID]
      ,[WH_ID]
      ,[WH_NAME]
      ,[PROD_ID]
      ,[INV_OUT]
      ,[INV_IN]
      ,[QTY_ON_HAND]
      ,[REORDER_LEVEL]
      ,[AS_OF_YEAR]
      ,[AS_OF_MONTH]
      ,[AS_OF_DATE]
  FROM [AP_INVENTORY].[TRANSACTION].[WAREHOUSE]
  WHERE [AS_OF_YEAR] IN('2005')
  AND  [INV_ID] = 'INV1'
  AND  [LOC_ID] = 'LOC1'
  AND  [WH_ID] = 'WH111'
  AND [PROD_ID] = 'P033'
  ORDER BY  
	   [AS_OF_YEAR]
      ,[AS_OF_MONTH]
	  ,[INV_ID]
      ,[LOC_ID]
      ,[WH_ID]
      ,[WH_NAME]
      ,[PROD_ID]
GO

/**********************/
/* VALIDATION QUERIES */
/**********************/

SELECT [AS_OF_YEAR],
	[AS_OF_MONTH],
	[LOC_ID],
	[INV_ID],
	[PROD_ID],
	[WH_ID],
	SUM([QTY_ON_HAND]) AS QTY_ACROSS_WH
FROM [TRANSACTION].[WAREHOUSE]
GROUP BY [AS_OF_YEAR],
	[AS_OF_MONTH],
	[LOC_ID],
	[INV_ID],
	[PROD_ID],
	[WH_ID]
ORDER BY [AS_OF_YEAR],
	[AS_OF_MONTH],[WH_ID],
	[LOC_ID],
	[PROD_ID]
GO

/*************/
/* INVENTORY */
/*************/

USE [AP_INVENTORY]
GO

TRUNCATE TABLE [TRANSACTION].[INVENTORY]
GO

INSERT INTO [TRANSACTION].[INVENTORY]
SELECT [LOC_ID]
      ,[INV_ID]
      ,[PROD_ID]
      ,SUM([QTY_ON_HAND])
	  ,EOMONTH([AS_OF_DATE]) AS EOM_DATE
FROM [TRANSACTION].[WAREHOUSE]
WHERE [AS_OF_DATE] = EOMONTH([AS_OF_DATE])
GROUP BY [LOC_ID]
      ,[INV_ID]
      ,[PROD_ID]
	  ,EOMONTH([AS_OF_DATE])
ORDER BY [LOC_ID]
      ,[INV_ID]
      ,[PROD_ID];
GO

/***************/
/* QUICK CHECK */
/***************/

SELECT [LOC_ID]
      ,[INV_ID]
      ,[PROD_ID]
      ,[UNITS]
      ,CONVERT(DATE,[AS_OF_DATE]) AS INVENTORY_DATE
  FROM [AP_INVENTORY].[TRANSACTION].[INVENTORY]
  WHERE PROD_ID = 'P033'
AND YEAR(AS_OF_DATE) = 2002
AND LOC_ID = 'LOC1'
AND INV_ID IN('INV1','INV2')
ORDER BY [LOC_ID]
      ,[INV_ID]
      ,[PROD_ID]
	   ,[AS_OF_DATE]
      ,[UNITS]
GO
     





