USE [master]
GO

/****************************************************************/
/* NOTE: IF YOU ONLY HAVE A SINGLE DRIVE, CHANGE D: DRIVE to C: */
/****************************************************************/

CREATE DATABASE [AP_INVENTORY]
CONTAINMENT = NONE
ON  PRIMARY 
( 
	NAME = N'AP_INVENTORY_PRIMARY', 
	FILENAME = N'D:\APRESS_DATABASES\AP_INVENTORY\PRIMARY\AP_INVENTORY_PRIMARY.mdf' , 
	SIZE = 1024000KB , 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 65536KB 
), 
 FILEGROUP [AP_INVENTORY_FG] 
( 
NAME = N'AP_INVENTORY_DATA', 
FILENAME = N'D:\APRESS_DATABASES\AP_INVENTORY\DATA\AP_INVENTORY_DATA.ndf' , 
SIZE = 2048000KB, 
MAXSIZE = UNLIMITED, 
FILEGROWTH = 65536KB
)
LOG ON 
( 
NAME = N'AP_INVENTORY_LOG', 
FILENAME = N'D:\APRESS_DATABASES\AP_INVENTORY\LOGS\AP_INVENTORY_LOG.ldf' , 
SIZE = 1024000KB , MAXSIZE = 2048GB 
,FILEGROWTH = 65536KB
)
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

