USE [master]
GO

CREATE DATABASE [APSales]
 CONTAINMENT = NONE
ON  PRIMARY 
( 
	NAME = N'AP_SALES_PRIMARY', 
	FILENAME = N'D:\APRESS_DATABASES\AP_SALES\PRIMARY\AP_SALES_PRIMARY.mdf' , 
	SIZE = 1024000KB , 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 65536KB
), 
FILEGROUP [AP_SALES_FG]  DEFAULT
(
	NAME = N'AP_SALES_DATA', 
	FILENAME = N'D:\APRESS_DATABASES\AP_SALES\DATA\AP_SALES_DATA.ndf',
	SIZE = 22298624KB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 65536KB
	), 
FILEGROUP [APSAlesMemOptimized] CONTAINS MEMORY_OPTIMIZED_DATA  DEFAULT
(
	NAME = N'APSalesMemoOptData',
	FILENAME = N'D:\APRESS_DATABASES\AP_SALES\MEMORYOPT\AP_SALES_MEMOPT.mdf',
	MAXSIZE = UNLIMITED
)
LOG ON 
(
	NAME = N'AP_SALES_LOG',
	FILENAME = N'D:\APRESS_DATABASES\AP_SALES\LOGS\AP_SALES_LOG.ldf',
	SIZE = 142974976KB,
	MAXSIZE = 2048GB,
	FILEGROWTH = 65536KB
)
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO


