USE [master]
GO

CREATE DATABASE [AP_PLANT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( 
NAME = N'AP_PLANT_PRIMARY', 
FILENAME = N'D:\APRESS_DATABASES\AP_PLANT\PRIMARY\AP_PLANT_PRIMARY.mdf' , 
SIZE = 1024000KB , 
MAXSIZE = UNLIMITED, 
FILEGROWTH = 65536KB
), 
 FILEGROUP [AP_PLANT_FG]  DEFAULT
( 
NAME = N'AP_PLANT_DATA', 
FILENAME = N'D:\APRESS_DATABASES\AP_PLANT\DATA\AP_PLANT_DATA.ndf' , 
SIZE = 2048000KB , 
MAXSIZE = UNLIMITED, 
FILEGROWTH = 65536KB
)
 LOG ON 
( 
NAME = N'AP_PLANT_LOG', 
FILENAME = N'D:\APRESS_DATABASES\AP_PLANT\LOGS\AP_PLANT_LOG.ldf' , 
SIZE = 1024000KB , 
MAXSIZE = 2048GB , 
FILEGROWTH = 65536KB
)
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AP_PLANT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AP_PLANT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AP_PLANT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AP_PLANT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AP_PLANT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AP_PLANT] SET ARITHABORT OFF 
GO

ALTER DATABASE [AP_PLANT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AP_PLANT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AP_PLANT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AP_PLANT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AP_PLANT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AP_PLANT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AP_PLANT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AP_PLANT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AP_PLANT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AP_PLANT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AP_PLANT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AP_PLANT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AP_PLANT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AP_PLANT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AP_PLANT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AP_PLANT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AP_PLANT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AP_PLANT] SET RECOVERY FULL 
GO

ALTER DATABASE [AP_PLANT] SET  MULTI_USER 
GO

ALTER DATABASE [AP_PLANT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AP_PLANT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AP_PLANT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AP_PLANT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AP_PLANT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AP_PLANT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AP_PLANT] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AP_PLANT] SET  READ_WRITE 
GO


