USE [AP_PLANT]
GO

/*****************/
/* CREATE SCHEMA */
/*****************/

DROP SCHEMA IF EXISTS DIM
GO

CREATE SCHEMA DIM
GO

DROP SCHEMA IF EXISTS FACT
GO

CREATE SCHEMA FACT
GO

/*********/
/* PLANT */
/*********/

DROP TABLE IF EXISTS [DIM].[PLANT]
GO

CREATE TABLE [DIM].[PLANT](
	[PLANT_KEY] [int] IDENTITY(1,1) NOT NULL,
	[PLANT_ID] [varchar](8) NOT NULL,
	[PLANT_NAME] [varchar](64) NOT NULL,
	[PLANT_DESCRIPTION] [varchar](64) NOT NULL
) ON [AP_PLANT_FG]
GO


/************/
/* CALENDAR */
/************/

DROP TABLE IF EXISTS [DIM].[CALENDAR]
GO

CREATE TABLE [DIM].[CALENDAR](
	[CALENDAR_KEY] [int] NOT NULL,
	[CALENDAR_DATE] DATE NOT NULL,
	[CALENDAR_YEAR] SMALLINT NOT NULL,
	[CALENDAR_QTR] SMALLINT NOT NULL,
	[CALENDAR_MONTH] SMALLINT NOT NULL,
	[CALENDAR_DAY] SMALLINT NOT NULL
) ON [AP_PLANT_FG]
GO

/*****************/
/* CALENDAR VIEW */
/*****************/

USE [AP_PLANT]
GO

DROP VIEW IF EXISTS [DIM].[CALENDAR_VIEW]
GO

CREATE VIEW [DIM].[CALENDAR_VIEW]
AS
SELECT [CALENDAR_KEY],
       [CALENDAR_YEAR],
       [CALENDAR_QTR],
       	  ,CASE       
		WHEN [CALENDAR_QTR] = 1 THEN '1st Quarter'
		WHEN [CALENDAR_QTR] = 2 THEN '2nd Quarter'
		WHEN [CALENDAR_QTR] = 3 THEN '3rd Quarter'
		WHEN [CALENDAR_QTR] = 4 THEN '4th Quarter'
		END AS QUARTER_NAME
      ,[CALENDAR_MONTH]
	  ,CASE       
		WHEN [CALENDAR_MONTH] = 1 THEN 'Jan'
		WHEN [CALENDAR_MONTH] = 2 THEN 'Feb'
		WHEN [CALENDAR_MONTH] = 3 THEN 'Mar'
		WHEN [CALENDAR_MONTH] = 4 THEN 'Apr'
		WHEN [CALENDAR_MONTH] = 5 THEN 'May'
		WHEN [CALENDAR_MONTH] = 6 THEN 'Jun'
		WHEN [CALENDAR_MONTH] = 7 THEN 'Jul'
		WHEN [CALENDAR_MONTH] = 8 THEN 'Aug'
		WHEN [CALENDAR_MONTH] = 9 THEN 'Sep'
		WHEN [CALENDAR_MONTH] = 10 THEN 'Oct'
		WHEN [CALENDAR_MONTH] = 11 THEN 'Nov'
		WHEN [CALENDAR_MONTH] = 12 THEN 'Dec'
		END AS MONTH_ABBREV
	  ,CASE       
		WHEN [CALENDAR_MONTH] = 1 THEN 'January'
		WHEN [CALENDAR_MONTH] = 2 THEN 'February'
		WHEN [CALENDAR_MONTH] = 3 THEN 'March'
		WHEN [CALENDAR_MONTH] = 4 THEN 'April'
		WHEN [CALENDAR_MONTH] = 5 THEN 'May'
		WHEN [CALENDAR_MONTH] = 6 THEN 'June'
		WHEN [CALENDAR_MONTH] = 7 THEN 'July'
		WHEN [CALENDAR_MONTH] = 8 THEN 'August'
		WHEN [CALENDAR_MONTH] = 9 THEN 'September'
		WHEN [CALENDAR_MONTH] = 10 THEN 'October'
		WHEN [CALENDAR_MONTH] = 11 THEN 'November'
		WHEN [CALENDAR_MONTH] = 12 THEN 'December'
		END AS MONTH_NAME

      ,[CALENDAR_DATE]

FROM   [DIM].[CALENDAR];
GO

/****************/
/* MANUFACTURER */
/****************/

DROP TABLE IF EXISTS [DIM].[MANUFACTURER]
GO

CREATE TABLE [DIM].[MANUFACTURER](
	[MANUFACTURER_KEY] [int] IDENTITY(1,1) NOT NULL,
	[MANUFACTURER_ID] [varchar](8) NOT NULL,
	[MANUFACTURER_NAME] [varchar](64) NOT NULL
) ON [AP_PLANT_FG]
GO

/*************/
/* EQUIPMENT */
/*************/

DROP TABLE IF EXISTS [DIM].[EQUIPMENT]
GO

CREATE TABLE [DIM].[EQUIPMENT](
	[EQUIPMENT_KEY] INTEGER  NOT NULL,
	[EQUIPMENT_ID] [varchar](8) NOT NULL,
	[SERIAL_NO] [varchar](34) NULL,
	[EQUIP_ABBREV] [varchar](3) NULL,
	[EQUIPMENT_TYPE] [varchar](2) NOT NULL,
	[MANUFACTURER_ID] [varchar](8) NOT NULL
) ON [AP_PLANT_FG]
GO


/*****************/
/* EQUIPMENT OLD */
/*****************/
/*

DROP TABLE IF EXISTS [DIM].[EQUIPMENT]
GO

CREATE TABLE [DIM].[EQUIPMENT](
	[EQUIPMENT_KEY] [int] IDENTITY(1,1) NOT NULL,
	[PLANT_ID] [varchar](8) NOT NULL,
	[LOCATION_ID] [varchar](8) NOT NULL,
	[EQUIPMENT_ID] [varchar](8) NOT NULL,
	[EQUIPMENT_TYPE] [varchar](2) NOT NULL
) ON [AP_PLANT_FG]
GO
*/

/*********************/
/* EQUIPMENT FAILURE */
/*********************/

DROP TABLE IF EXISTS [FACT].[EQUIPMENT_FAILURE]
GO

CREATE TABLE [FACT].[EQUIPMENT_FAILURE](
	[CALENDAR_KEY] [int] NOT NULL,
	[LOCATION_KEY] [int] NOT NULL,
	[EQUIPMENT_KEY] [int] NOT NULL,
	[EQUIPMENT_TYPE_KEY] [int] NOT NULL,
	[FAILURE] [int] NOT NULL
) ON [AP_PLANT_FG]
GO

 
/******************/
/* EQUIPMENT TYPE */
/******************/

/******************************************/
/* EQUIPMENT TYPE TABLE AS A TYPE 1 SCD   */
/* JUST OVER-WRITE or DELETE NEW OLD ROWS */
/******************************************/

DROP TABLE IF EXISTS [DIM].[EQUIPMENT_TYPE]
GO

CREATE TABLE [DIM].[EQUIPMENT_TYPE](
	[EQUIPMENT_TYPE_KEY] [int] IDENTITY(1,1) NOT NULL,
	[EQUIPMENT_TYPE] [varchar](2) NOT NULL,
	[EQUIPMENT_DESCRIPTION] [varchar](64) NOT NULL
) ON [AP_PLANT_FG]
GO

USE [AP_PLANT]
GO

/********************************/
/* ENHANCE EQUIPMENT TYPE TABLE */
/********************************/

DROP TABLE IF EXISTS [DIM].[EQUIPMENT_TYPE_ENHANCED]
GO

CREATE TABLE [DIM].[EQUIPMENT_TYPE_ENHANCED](
	[EQUIPMENT_TYPE_KEY] [int] IDENTITY(1,1) NOT NULL,
	[EQUIPMENT_TYPE] [varchar](2) NOT NULL,
	[EQUIPMENT_DESCRIPTION] [varchar](64) NOT NULL,
	[INSERT_BY] [varchar](64) NOT NULL,
	[INSERT_DATE] [varchar](64) NOT NULL,
	[UPDATE_BY] [varchar](64) NOT NULL,
	[UPDATE_DATE] [varchar](64) NOT NULL
) ON [AP_PLANT_FG]
GO

/****************************************/
/* EQUIPMENT TYPE TABLE AS A TYPE 2 SCD */
/****************************************/

DROP TABLE IF EXISTS [DIM].[EQUIPMENT_TYPE2_SCD]
GO

CREATE TABLE [DIM].[EQUIPMENT_TYPE2_SCD](
	[EQUIPMENT_TYPE_KEY] [int] IDENTITY(1,1) NOT NULL,
	[EQUIPMENT_TYPE] [varchar](2) NOT NULL,
	[EQUIPMENT_DESCRIPTION] [varchar](64) NOT NULL,
	[START_DATE] [DATE] NOT NULL,
	[END_DATE] [DATE] NULL,
	[INSERT_BY] [varchar](64) NOT NULL,
	[INSERT_DATE] [varchar](64) NOT NULL,
	[UPDATE_BY] [varchar](64) NOT NULL,
	[UPDATE_DATE] [varchar](64) NOT NULL,
) ON [AP_PLANT_FG]
GO

/****************************************/
/* EQUIPMENT TYPE TABLE AS A TYPE 3 SCD */
/****************************************/

DROP TABLE IF EXISTS [DIM].[EQUIPMENT_TYPE3_SCD]
GO

CREATE TABLE [DIM].[EQUIPMENT_TYPE3_SCD](
	[EQUIPMENT_TYPE_KEY] [int] IDENTITY(1,1) NOT NULL,
	[EQUIPMENT_TYPE] [varchar](2) NOT NULL,
	[OLD_EQUIPMENT_TYPE] [varchar](2) NOT NULL,
	[EQUIPMENT_DESCRIPTION] [varchar](64) NOT NULL,
	[OLD_EQUIPMENT_DESCRIPTION] [varchar](64) NOT NULL,
	[START_DATE] [DATE] NOT NULL,
	[END_DATE] [DATE] NULL,
	[INSERT_BY] [varchar](64) NOT NULL,
	[INSERT_DATE] [varchar](64) NOT NULL,
	[UPDATE_BY] [varchar](64) NOT NULL,
	[UPDATE_DATE] [varchar](64) NOT NULL,
) ON [AP_PLANT_FG]
GO

/*************/
/* GENERATOR */
/*************/

DROP TABLE IF EXISTS [DIM].[GENERATOR]
GO

CREATE TABLE [DIM].[GENERATOR](
	[GENERATOR_KEY] [int] IDENTITY(1000,1) NOT NULL,
--	[EQUIPMENT_KEY] [int] NULL,
	[PLANT_ID] [varchar](8)         NOT NULL,
	[LOCATION_ID] [varchar](8)      NOT NULL,
	[EQUIPMENT_ID] [varchar](8)     NOT NULL,
	[GENERATOR_ID] [varchar](8)     NOT NULL,
	[GENERATOR_NAME] [varchar](128) NOT NULL,
	[TEMPERATURE] FLOAT             NOT NULL,
	[VOLTAGE] FLOAT                 NOT NULL,
	[KVA]	FLOAT                   NOT NULL,
	[AMP]	FLOAT                   NOT NULL
) ON [AP_PLANT_FG]
GO

/***********/
/* TURBINE */
/***********/

DROP TABLE IF EXISTS [DIM].[TURBINE]
GO

CREATE TABLE [DIM].[TURBINE](
	[TURBINE_KEY] [int] IDENTITY(2000,1) NOT NULL,
--	[EQUIPMENT_KEY] [int] NULL,
	[PLANT_ID] [varchar](8) NOT NULL,
	[LOCATION_ID] [varchar](8) NOT NULL,
	[EQUIPMENT_ID] [varchar](8) NOT NULL,
	[TURBINE_ID] [varchar](8) NOT NULL,
	[TURBINE_NAME] [varchar](128) NOT NULL,
	[VOLTAGE] FLOAT NOT NULL,
	[AMPS] FLOAT NOT NULL,
	[RPM]  FLOAT NOT NULL
) ON [AP_PLANT_FG]
GO

/************/
/* LOCATION */
/************/

DROP TABLE IF EXISTS [DIM].[LOCATION]
GO

CREATE TABLE [DIM].[LOCATION](
	[LOCATION_KEY] [int] IDENTITY(1,1) NOT NULL,
	[PLANT_ID] [varchar](8) NOT NULL,
	[LOCATION_ID] [varchar](8) NOT NULL,
	[LOCATION_NAME] [varchar](128) NOT NULL
) ON [AP_PLANT_FG]
GO

/*********/
/* MOTOR */
/*********/

DROP TABLE IF EXISTS [DIM].[MOTOR]
GO

CREATE TABLE [DIM].[MOTOR](
	[MOTOR_KEY] [int] IDENTITY(3000,1) NOT NULL,
--	[EQUIPMENT_KEY] [int] NULL,
	[PLANT_ID] [varchar](8) NOT NULL,
	[LOCATION_ID] [varchar](8) NOT NULL,
	[EQUIPMENT_ID] [varchar](8) NOT NULL,
	[MOTOR_ID] [varchar](8) NOT NULL,
	[MOTOR_NAME] [varchar](128) NOT NULL,
	[VOLTAGE] FLOAT NOT NULL,
	[RPM] FLOAT NOT NULL
) ON [AP_PLANT_FG]
GO

DROP TABLE IF EXISTS [DIM].[VALVE]
GO

CREATE TABLE [DIM].[VALVE](
	[VALVE_KEY] [int] IDENTITY(4000,1) NOT NULL,
--	[EQUIPMENT_KEY] [int] NULL,
	[PLANT_ID] [varchar](8) NOT NULL,
	[LOCATION_ID] [varchar](8) NOT NULL,
	[EQUIPMENT_ID] [varchar](8) NOT NULL,
	[VALVE_ID] [varchar](8) NOT NULL,
	[VALVE_NAME] [varchar](128) NOT NULL,
	[STEAM_TEMP] FLOAT NOT NULL,
	[STEAM_PSI] FLOAT NOT NULL
) ON [AP_PLANT_FG]
GO
