USE AP_PLANT
GO

/************************/
/* CREATED: 3/22/2022   */
/* MODIFIED: 05/20/2022 */
/************************/

/*
	   ,UPPER (
		CONVERT(INT,CRYPT_GEN_RANDOM(1)
			) /	10) AS [TransactionQuantity]
*/

/****************************/
/* Runs in 8 seconds        */
/* Generates 1,227,200 rows */
/****************************/

TRUNCATE TABLE [FACT].[EQUIPMENT_FAILURE]
GO

INSERT INTO [FACT].[EQUIPMENT_FAILURE]
SELECT C.CALENDAR_KEY,
	L.[LOCATION_KEY],
	G.[GENERATOR_KEY] AS EQUIPMENT_KEY,
	1 AS [EQUIPMENT_TYPE_KEY],
	UPPER (
		CONVERT(INT,CRYPT_GEN_RANDOM(1)
			) /	10) AS FAILURE
FROM [DIM].[GENERATOR] G WITH (NOLOCK)
JOIN [DIM].[LOCATION] L WITH (NOLOCK)
	ON G.LOCATION_ID = L.LOCATION_ID
CROSS JOIN [DIM].[CALENDAR] C
UNION ALL
SELECT C.CALENDAR_KEY,
	L.[LOCATION_KEY],
	M.[MOTOR_KEY] AS EQUIPMENT_KEY,
	2 AS [EQUIPMENT_TYPE_KEY],
	UPPER (
		CONVERT(INT,CRYPT_GEN_RANDOM(1)
			) /	10) AS FAILURE
FROM [DIM].[MOTOR] M WITH (NOLOCK)
JOIN [DIM].[LOCATION] L WITH (NOLOCK)
	ON M.LOCATION_ID = L.LOCATION_ID
CROSS JOIN [DIM].[CALENDAR] C WITH (NOLOCK)
UNION ALL
SELECT C.CALENDAR_KEY,
	L.[LOCATION_KEY],
	T.[TURBINE_KEY]             AS EQUIPMENT_KEY,
	3 AS [EQUIPMENT_TYPE_KEY],
	UPPER (
		CONVERT(INT,CRYPT_GEN_RANDOM(1)
			) /	10) AS FAILURE
FROM [DIM].[TURBINE] T WITH (NOLOCK)
JOIN [DIM].[LOCATION] L WITH (NOLOCK)
	ON T.LOCATION_ID = L.LOCATION_ID
CROSS JOIN [DIM].[CALENDAR] C WITH (NOLOCK)
UNION ALL
SELECT C.CALENDAR_KEY,
	L.[LOCATION_KEY],
	V.[VALVE_KEY]             AS EQUIPMENT_KEY,
	4 AS [EQUIPMENT_TYPE_KEY],
	UPPER (
		CONVERT(INT,CRYPT_GEN_RANDOM(1)
			) /	10) AS FAILUREE
FROM [DIM].[VALVE] V WITH (NOLOCK)
JOIN [DIM].[LOCATION] L WITH (NOLOCK)
	ON V.LOCATION_ID = L.LOCATION_ID
CROSS JOIN [DIM].[CALENDAR] C WITH (NOLOCK)
GO