
SELECT EFSTG.[CALENDAR_KEY]
      ,EFSTG.[EQUIPMENT_KEY]
      ,EFSTG.[EQUIPMENT_TYPE]

	  ,L.[LOCATION_KEY]
      ,G.[GENERATOR_KEY]
--  ,T.[TURBINE_KEY]
 --     ,[MOTOR_KEY]
--,[VALVE_KEY]


      ,EFSTG.[PLANT_ID]
      ,EFSTG.[LOCATION_ID]
      ,EFSTG.[EQUIPMENT_ID]
      ,EFSTG.[CALENDAR_DATE]
      ,EFSTG.[NUMBER_EVENTS]
  FROM [FACT].[EQUIPMENT_FAILURE_STG] EFSTG
  JOIN [DIM].[LOCATION] L
  ON EFSTG.LOCATION_ID = L.LOCATION_ID
  JOIN [DIM].[GENERATOR] G
  ON EFSTG.EQUIPMENT_KEY = G.EQUIPMENT_KEY
  JOIN [DIM].[TURBINE] T 
  ON EFSTG.EQUIPMENT_KEY = T.EQUIPMENT_KEY
--  JOIN [DIM].[MOTOR] M
--  ON EFSTG.EQUIPMENT_KEY = M.[EQUIPMENT_KEY]
 GO

 
USE [AP_PLANT]
GO

SELECT E.[EQUIPMENT_KEY]
--	,G.GENERATOR_KEY
	,M.MOTOR_KEY
    ,E.[PLANT_ID]
    ,E.[LOCATION_ID]
    ,E.[EQUIPMENT_ID]
    ,E.[EQUIPMENT_TYPE]
  FROM [DIM].[EQUIPMENT] E
--  JOIN [DIM].[GENERATOR] G
--  ON E.EQUIPMENT_KEY = G.EQUIPMENT_KEY
  JOIN [DIM].[MOTOR] M
  ON E.EQUIPMENT_KEY = M.EQUIPMENT_KEY
GO



/*
SELECT DISTINCT EQUIPMENT_KEY,EQUIPMENT_ID FROM [FACT].[EQUIPMENT_FAILURE_STG]
WHERE EQUIPMENT_TYPE = '03'
ORDER BY 1

SELECT distinct EQUIPMENT_KEY AS TURBINE_EQUIPMENT_KEY,EQUIPMENT_ID FROM [DIM].[TURBINE]
ORDER BY 1
*/