USE [master]
GO

/****** Object:  Database [APInventoryWarehouse]    Script Date: 7/7/2023 12:00:18 PM ******/
CREATE DATABASE [APInventoryWarehouse]
 CONTAINMENT = NONE
 ON  PRIMARY 
( 
NAME = N'AP_INVENTORY_WAREHOUSE_PRIMARY', 
FILENAME = N'D:\APRESS_DATABASES\AP_INVENTORY_WAREHOUSE\PRIMARY\AP_INVENTORY_WAREHOUSE_PRIMARY.mdf' ,
SIZE = 1024000KB , 
MAXSIZE = UNLIMITED, 
FILEGROWTH = 65536KB
), 
 FILEGROUP [AP_INVENTORY_WAREHOUSE_FG]  DEFAULT
( 
NAME = N'AP_INVENTORY_WAREHOUSE_DATA', 
FILENAME = N'D:\APRESS_DATABASES\AP_INVENTORY_WAREHOUSE\DATA\AP_INVENTORY_WAREHOUSE_DATA.ndf' , 
SIZE = 2048000KB , 
MAXSIZE = UNLIMITED, 
FILEGROWTH = 65536KB
)
 LOG ON 
( 
NAME = N'AP_INVENTORY_WAREHOUSE_LOG', 
FILENAME = N'D:\APRESS_DATABASES\AP_INVENTORY_WAREHOUSE\LOGS\AP_INVENTORY_WAREHOUSE_LOG.ldf' , 
SIZE = 30625792KB ,
MAXSIZE = 2048GB ,
FILEGROWTH = 102400KB
)
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

